### ISSUE TITLE
Cannot dump definitions which have no class nor factory.

### ISSUE THREAD

**Issue by Luuka** [fduch/workflow-bundle#1]
Hi,

We try to use your bundle but we got a problem.

We use this conf *:

```
workflow:
    workflows:
        order_publishing:
            marking_store:
                type: property_accessor
            supports:
                - Bundle\Entity\Order
            places:
                - draft
                - spellchecked
                - published
            transitions:
                spellcheck:
                    from: draft
                    to:   spellchecked
                publish:
                    from: spellchecked
                    to:   published
```

But we got this error 

```
RuntimeException in PhpDumper.php line 1360:
Cannot dump definitions which have no class nor factory.
in PhpDumper.php line 1360
at PhpDumper->dumpValue(object(DefinitionDecorator)) in PhpDumper.php line 765
at PhpDumper->addNewInstance('workflow.order_publishing', object(Definition), 'return ', '$this->services['workflow.order_publishing'] = ') in PhpDumper.php line 400
at PhpDumper->addServiceInstance('workflow.order_publishing', object(Definition)) in PhpDumper.php line 653
at PhpDumper->addService('workflow.order_publishing', object(Definition)) in PhpDumper.php line 680
at PhpDumper->addServices() in PhpDumper.php line 148
at PhpDumper->dump(array('class' => 'appDevDebugProjectContainer', 'base_class' => 'Container', 'file' => '/var/www/app-symfony/symfony/app/cache/dev/appDevDebugProjectContainer.php')) in bootstrap.php.cache line 2716
at Kernel->dumpContainer(object(ConfigCache), object(ContainerBuilder), 'appDevDebugProjectContainer', 'Container') in bootstrap.php.cache line 2632
at Kernel->initializeContainer() in bootstrap.php.cache line 2409
at Kernel->boot() in bootstrap.php.cache line 2440
at Kernel->handle(object(Request)) in app_dev.php line 31
```

We try to investigate and the issue seems to come from the definition of `workflow.marking_store.property_accessor`. Do you have any clue on this ? 

Thanks.

**Comment by fduch** [comment]
Hi @Luuka!

Sorry for delay.

I've checked your config in Symfony 2.8.5 environment and container was dumped successfully. 
I've also wondered that your stacktrace contains that string:

```
at PhpDumper->dumpValue(object(DefinitionDecorator)) in PhpDumper.php line 765
```

because normally ResolveDefinitionTemplatesPass's work is to resolve DefinitionDecorator instances to Definition instances, - so in fact PhpDumper should not work with DefinitionDecorator object but only with Definition ones instead.

Can you detect (with the help of breakpoint probably) what kind of DefinitionDecorator instance is passed to PhpDumper::dumpValue method according to your exception trace right before Exception is thrown?

Which Symfony version do you use? Do the both fduch/workflow-bundle and symfony/worklfow components are installed properly in your application?

**Comment by slaci** [comment]
Hi

I tried to use this workflow bundle today and I get this error too. The config is similar, nothing special.

Sf 2.7
The workflow component (c36cc44) and your bundle (78c3ccc) is at dev versions.

Before the exception thrown, this is the $value object:

``` php
class Symfony\Component\DependencyInjection\DefinitionDecorator#4489 (20) {
  private $parent =>
  string(40) "workflow.marking_store.property_accessor"
  private $changes =>
  array(0) {
  }
  private $class =>
  NULL
  private $file =>
  NULL
  private $factory =>
  NULL
  private $factoryClass =>
  NULL
  private $factoryMethod =>
  NULL
  private $factoryService =>
  NULL
  private $scope =>
  string(9) "container"
  private $properties =>
  array(0) {
  }
  private $calls =>
  array(0) {
  }
  private $configurator =>
  NULL
  private $tags =>
  array(0) {
  }
  private $public =>
  bool(true)
  private $synthetic =>
  bool(false)
  private $abstract =>
  bool(false)
  private $synchronized =>
  bool(false)
  private $lazy =>
  bool(false)
  private $decoratedService =>
  NULL
  protected $arguments =>
  array(0) {
  }
}
```

The exception is thrown because:

``` php
$class = $value->getClass();
            if (null === $class) {
```

**Comment by wakqasahmed** [comment]
Any solution for it? I have the exact same issue.

**Comment by slaci** [comment]
I didnt check why it happens. I guess it should populate the params based on a base service, but it doesnt do.
So the easy lazy solution is to create a new service based on a marker class, so the bug is skipped:

In the workflow config:

```
...
marking_store:
    service: my_marking_service
```

In services.yml:

```
services:
    my_marking_service:
        class: Symfony\Component\Workflow\MarkingStore\ScalarMarkingStore
        #arguments: ['markingpropname', '@property_accessor']
```

Something like this... arguments are optional ofc (and not sure the default sf service for the property accessor called that, but its optional anyway).
The other built in marking class is PropertyAccessorMarkingStore from the same namespace, but that is very weird I think.
