### ISSUE TITLE
Marking accessor does not support custom arguments

### ISSUE THREAD

**Issue by sigzegv** [fduch/workflow-bundle#4]
When I try to specify a custom argument for property_accessor in marking_store (to send custom field intead of default "marking" value), the bundle fails to generate the service definition (it requires an array, but custom argument sent a string).

Looks like it's supported by SF framework in 3.2 :
https://github.com/symfony/symfony/issues/19936

**Comment by fduch** [comment]
I've just tested the configuration like this: 

```
workflow:
    workflows:
        simple:
            marking_store:
                type: property_accessor
                arguments: status
            supports:
                - Test\Bundle\Entity\Subject
            places:~
            transitions: ~
```

and it works for me. 
If i pass arguments as array (without normalization of `arguments` node on compile time) like this:

```
workflow:
    workflows:
        simple:
            marking_store:
                type: property_accessor
                arguments: 
                    - status
            supports:
                - Test\Bundle\Entity\Subject
            places:~
            transitions: ~
```

and it also works.

I've tested with symfony/framework-bundle  v2.8.9 

@Sigzegv could you please specify configuration that makes build broken and your symfony/framework-bundle version?
