### ISSUE TITLE
Update bundle to support new changes in 3.2's FrameworkBundle

### ISSUE THREAD

**Issue by fduch** [fduch/workflow-bundle#6]
After BC-breaks in Workflow component and FrameworkBundle https://github.com/symfony/symfony/pull/20462
there is a need to backport the changes from FrameworkBundle into the fduch/workflow-bundle.

This change requires split of the current master branch into 1.x one for old version of FrameworkBundle and new master for new version support.

**Comment by wakqasahmed** [comment]
Updating to latest version ^1.0 produces following error for me:

```
[Symfony\Component\Debug\Exception\ContextErrorException]                    
  Catchable Fatal Error: Argument 1 passed to Symfony\Component\Workflow\Defi  
  nition::__construct() must be of the type array, none given
```

Even though I have update my service based on previous issue https://github.com/fduch/workflow-bundle/issues/1 (below is my configuration)

```
services:
    workflow.guard:
        class: Acme\Bundle\DemoBundle\Workflow\GuardListener
        tags:
            - { name: kernel.event_subscriber }
        arguments: ['@security.authorization_checker']
    acme_marking_service:
        class: Symfony\Component\Workflow\MarkingStore\SingleStateMarkingStore
        #arguments: ['markingpropname', '@property_accessor']
```

Is it related to this opened issue?
